backend/.idea/dataSources.xml
backend/.idea/sqldialects.xml
backend/.idea/vcs.xml
backend/estate.sql

<데이터베이스 스키마, 테이블, 샘플 추가>
- 설계한 ERD 대로 데이터베이스의 테이블 구조 잡았습니다.
- 샘플 데이터를 넣어두었습니다.

Feat: Add Database schema, tables and samples

---

backend/estate.sql
backend/src/main/java/org/scoula/config/RootConfig.java
backend/src/main/java/org/scoula/config/ServletConfig.java
backend/src/main/java/org/scoula/dictionary/controller/DictionaryController.java
backend/src/main/java/org/scoula/dictionary/domain/DictionaryDTO.java
backend/src/main/java/org/scoula/dictionary/domain/DictionaryVO.java
backend/src/main/java/org/scoula/dictionary/mapper/DictionaryMapper.java
backend/src/main/java/org/scoula/dictionary/service/DictionaryService.java
backend/src/main/java/org/scoula/dictionary/service/DictionaryServiceImpl.java
backend/src/main/resources/org/scoula/dictionary/mapper/DictionaryMapper.xml

부동산 용어 사전에 관한 REST API 개발입니다.
- Dictionary의 domain, controller, service, mapper 등

Feat : add to REST API about Dictionary

---

backend/estate.sql
backend/src/main/java/org/scoula/config/RootConfig.java
backend/src/main/java/org/scoula/config/ServletConfig.java
backend/src/main/java/org/scoula/faq/controller/FaqController.java
backend/src/main/java/org/scoula/faq/domain/FaqDTO.java
backend/src/main/java/org/scoula/faq/domain/FaqVO.java
backend/src/main/java/org/scoula/faq/mapper/FaqMapper.java
backend/src/main/java/org/scoula/faq/service/FaqService.java
backend/src/main/java/org/scoula/faq/service/FaqServiceImpl.java
backend/src/main/resources/org/scoula/faq/mapper/FaqMapper.xml

FAQ에 대한 REST API 구현입니다.
- FAQ의 domain, controller, service, mapper 등

Feat : add to REST API about FAQ

---

frontend/src/api/dictionaryApi.js
frontend/src/pages/study/dictionary/DictionaryDetailPage.vue
frontend/src/pages/study/dictionary/DictionaryListPage.vue
frontend/src/router/index.js

(완료)
- Dictionary 목록, 세부 페이지 추가
- axios 연동
- dictionary script 내용 수정
(예정)
- frontend 브랜치에서 테스트 예정

Feat : Add Dictionary script

---

frontend/src/api/faqApi.js
frontend/src/pages/study/FAQ/FAQDetailPage.vue
frontend/src/pages/study/FAQ/FAQListPage.vue
frontend/src/router/index.js

- FAQ 목록, 세부 페이지 생성
- axios 연동 
backend 와 병합해서 테스트 할 예정

Feat : Add FAQ Script

---

frontend/src/api/dictionaryApi.js
frontend/src/pages/study/dictionary/DictionaryDetailPage.vue
frontend/src/pages/study/dictionary/DictionaryListPage.vue
frontend/src/router/index.js

- dictionaryApi.js 내 'params' 삭제
- DictionaryDetailPage, DictionaryListPage 대문자 -> 소문자 수정
- index.js 경로 수정( ' / ' 추가)

FE feature dictionary script2

---

frontend/src/pages/study/dictionary/DictionaryListPage.vue
frontend/src/router/index.js

(완료)
- DictionaryListPage 수정
- index.js -> dictionary path 수정( ' / ' 추가)
(수정필요)
- dictionary/list 가면 f12 누르면 데이터베이스 내용이 보이는데 화면에는 안 보이는 상태

Fix: modify Dictionary script

---

backend/src/main/java/org/scoula/faq/controller/FaqController.java
backend/src/main/java/org/scoula/faq/mapper/FaqMapper.java
backend/src/main/java/org/scoula/faq/service/FaqService.java
backend/src/main/java/org/scoula/faq/service/FaqServiceImpl.java
backend/src/main/resources/org/scoula/faq/mapper/FaqMapper.xml

- FAQ REST API의 list 부분을 pagination 으로 수정하였습니다.
- dictionary 부분은 버그가 아니었습니다.

Fix : getlist converted to pagination in REST API of FAQ

---

backend/.gitignore
backend/src/main/java/org/scoula/faq/controller/FaqController.java
backend/src/main/java/org/scoula/faq/mapper/FaqMapper.java
backend/src/main/java/org/scoula/faq/service/FaqService.java
backend/src/main/java/org/scoula/faq/service/FaqServiceImpl.java
backend/src/main/resources/org/scoula/faq/mapper/FaqMapper.xml

- faq pagination 이 반영된 backend 브랜치를 frontend와 병합하여 테스트하기 위함입니다.

Merge : backend & frontend

---

frontend/package-lock.json
frontend/package.json
frontend/src/pages/study/dictionary/DictionaryListPage.vue

1. frontend/package.json에 hangul-js 추가
- DictionaryListPage에서 한글 자음 순서대로 표시하기 위해서 추가
2. DictionaryListPage 수정
- 한글 자음 순서대로 클릭하면 나오는 기능 추가
- 단어 검색 기능 추가

Feat: DictionaryListPage list, search

---

frontend/src/components/Header.vue

(완성)
1. Header > Study 드랍 다운 구현
(보완)
1. 드랍 다운 위에 마우스 위치 알 수 있게 색깔을 바꾸거나 밑줄이 생기거나 그런 기능 필요할듯 .. !!!

Feat: Header Study add  Dropdown

---

frontend/src/pages/app/Main.vue

Design : Main.vue , 카드 디자인 및 색상 변경, 아래 문구 추가 , 토막상식 버튼 생성

Design : Main.vue

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/Footer.vue
frontend/src/components/Header.vue
frontend/src/main.js
frontend/src/pages/study/commonsense/SenseListPage.vue
frontend/src/pages/study/dictionary/DictionaryDetailPage.vue
frontend/src/pages/study/dictionary/DictionaryListPage.vue

1. fontawesome 라이브러리 추가
2. dictionary 페이지 아이콘 추가
3. dictionary, common sense 페이지 줄 삭제
4. header 드롭다운 메뉴 서식 변경(볼드체, 밑줄), 고정
5. footer 내용 추가, 고정

Feat : Header, Footer Update 및 border-bottom Update

---

frontend/src/pages/Login.vue

Design: Login

---

frontend/src/pages/Login.vue
frontend/src/stores/userStore.js

Fix : script

---

frontend/src/pages/app/Main.vue

라우터가 아래 2개 카드 모두 동시 처리 돼서 
왼쪽 카드만 beforeCheckList로 이동하도록 해결

Fix : card's router

---

backend/estate.sql
backend/src/main/java/org/scoula/config/RootConfig.java
backend/src/main/java/org/scoula/config/ServletConfig.java
backend/src/main/java/org/scoula/dictionary/controller/DictionaryController.java
backend/src/main/java/org/scoula/like/dictionary/controller/LikeDictionaryController.java
backend/src/main/java/org/scoula/like/dictionary/domain/LikeDictionaryDTO.java
backend/src/main/java/org/scoula/like/dictionary/domain/LikeDictionaryVO.java
backend/src/main/java/org/scoula/like/dictionary/mapper/LikeDictionaryMapper.java
backend/src/main/java/org/scoula/like/dictionary/service/LikeDictionaryService.java
backend/src/main/java/org/scoula/like/dictionary/service/LikeDictionaryServiceImpl.java
backend/src/main/resources/org/scoula/like/dictionary/mapper/LikeDictionaryMapper.xml

부동산 용어사전 즐겨찾기에 대한 REST API 입니다.
- GET : /api/like/dictionary : 즐겨찾기 리스트 가져오기
- GET : /api/like/dictionary/{dicNo} : 해당 게시글 즐겨찾기로 추가

Feat : add to restapi like dictionary

---

frontend/src/api/preventionApi.js
frontend/src/pages/study/BeforeCheckListPage.vue
frontend/src/pages/study/PreventionDetailPage.vue
frontend/src/pages/study/PreventionListPage.vue
frontend/src/router/index.js

Feat : preventionList, preventionDetail
- 페이지 이름 변경 
beforeCheckList -> preventionList

Feat : preventionList, preventionDetail

---

frontend/package-lock.json
frontend/src/pages/app/Main.vue
frontend/src/pages/study/PreventionListPage.vue

Main 에서 "부동산 계약이 처음이라면?" 누르면 preventionList로 이동

Fix : main - prevention

---

backend/src/main/resources/org/scoula/map/mapper/MapMapper.xml
frontend/package-lock.json
frontend/src/main.js
frontend/src/pages/map/MainMap.vue

1. map type is available now
2. map resized based on the web size
3. reloading sql code is revised

Feat : maptype, map resized

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/DonutChart.vue
frontend/src/pages/app/Report.vue

Feat : Report template

---

backend/estate.sql
backend/src/main/java/org/scoula/map/domain/MapDetailDTO.java
backend/src/main/resources/org/scoula/map/mapper/MapMapper.xml
frontend/src/pages/map/MainMap.vue
frontend/src/pages/map/SearchBar.vue

1. current location is now available
2. DTO updated

map additional function is updated

---

backend/src/main/java/org/scoula/like/dictionary/controller/LikeDictionaryController.java
backend/src/main/java/org/scoula/like/dictionary/mapper/LikeDictionaryMapper.java
backend/src/main/java/org/scoula/like/dictionary/service/LikeDictionaryService.java
backend/src/main/java/org/scoula/like/dictionary/service/LikeDictionaryServiceImpl.java
backend/src/main/resources/org/scoula/like/dictionary/mapper/LikeDictionaryMapper.xml

부동산 용어사전에 대한 즐겨찾기 기능에 필요한 REST API를 업데이트 하였습니다.

Feat : update to REST API about like_dictionary

---

frontend/src/pages/map/LeftPanel.vue
frontend/src/pages/map/MapAnalyzing.vue

propertyNo, addr_sido/addr_dong/jibun_address/addr_lotNumber, buildingName 보내기

Feat : MapAnalyzing page form

---

backend/estate.sql
frontend/src/api/like/likeDictionaryApi.js
frontend/src/pages/study/dictionary/DictionaryListPage.vue

1. 즐겨찾기 추가, 삭제, 즐겨찾기만 보기
2. 즐겨찾기 저장

Feat : Liked-DicionaryPage

---

backend/src/main/java/org/scoula/like/report/controller/LikeReportController.java
backend/src/main/java/org/scoula/like/report/domain/LikeReportDTO.java
backend/src/main/java/org/scoula/like/report/domain/LikeReportVO.java
backend/src/main/java/org/scoula/like/report/mapper/LikeReportMapper.java
backend/src/main/java/org/scoula/like/report/service/LikeReportImpl.java
backend/src/main/java/org/scoula/like/report/service/LikeReportService.java
backend/src/main/java/org/scoula/report/domain/ReportDTO.java
backend/src/main/java/org/scoula/report/domain/ReportVO.java
backend/src/main/java/org/scoula/report/mapper/ReportMapper.java
backend/src/main/java/org/scoula/report/service/reportService.java
backend/src/main/java/org/scoula/report/service/reportServiceImpl.java
backend/src/main/resources/org/scoula/like/report/mapper/LikeReportMapper.xml
backend/src/main/resources/org/scoula/report/mapper/ReportMapper.xml

Be feature restapi member report

---

backend/src/main/java/org/scoula/report/domain/ReportDTO.java
backend/src/main/java/org/scoula/report/domain/ReportVO.java
backend/src/main/java/org/scoula/report/mapper/ReportMapper.java
backend/src/main/java/org/scoula/report/service/reportService.java
backend/src/main/java/org/scoula/report/service/reportServiceImpl.java
backend/src/main/resources/org/scoula/report/mapper/ReportMapper.xml

사전에 임의로 설정해둔 의존성 클래스 이름을 통일 시킴

Update : REST API about report

---

frontend/src/pages/mypage/MyReport.vue
frontend/src/pages/mypage/Mypage.vue
frontend/src/router/index.js

1. myreport 페이지 만들기
2. myreport 삭제, 정렬 드롭다운(날짜, 평가등급)

Feat : myreport page

---

frontend/src/pages/map/LeftPanel.vue
frontend/src/pages/map/MapAnalyzing.vue

1. property analysis form updated

Update : property analysis form updated

---

frontend/src/api/like/likeReportApi.js
frontend/src/pages/mypage/MyReport.vue

1. 데이터 로드 함수 수정
2. likeReportApi.js
3. 백엔드 서버에서 페이지네이션 구현되면 수정 예정

Feat : MyReport page Api

---

backend/src/main/java/org/scoula/config/RootConfig.java
backend/src/main/java/org/scoula/config/ServletConfig.java
backend/src/main/java/org/scoula/report/service/ReportService.java
backend/src/main/java/org/scoula/report/service/ReportServiceImpl.java
backend/src/main/java/org/scoula/safety_inspection/controller/SafetyInspectionController.java

Feat : REST API about report

---

backend/src/main/java/org/scoula/config/RootConfig.java
backend/src/main/java/org/scoula/config/ServletConfig.java
backend/src/main/java/org/scoula/like/report/controller/LikeReportController.java
backend/src/main/java/org/scoula/like/report/mapper/LikeReportMapper.java
backend/src/main/java/org/scoula/like/report/service/LikeReportImpl.java
backend/src/main/java/org/scoula/like/report/service/LikeReportService.java
backend/src/main/resources/org/scoula/like/report/mapper/LikeReportMapper.xml

레포트 REST API에 페이지네이션을 추가하였습니다.

Update : add to pagination in REST API about report

---

backend/estate.sql
backend/src/main/java/org/scoula/config/RootConfig.java
backend/src/main/java/org/scoula/config/ServletConfig.java
backend/src/main/java/org/scoula/like/property/controller/LikePropertyController.java
backend/src/main/java/org/scoula/like/property/domain/LikePropertyDTO.java
backend/src/main/java/org/scoula/like/property/domain/LikePropertyVO.java
backend/src/main/java/org/scoula/like/property/mapper/LikePropertyMapper.java
backend/src/main/java/org/scoula/like/property/service/LikePropertyService.java
backend/src/main/java/org/scoula/like/property/service/LikePropertyServiceImpl.java
backend/src/main/java/org/scoula/map/domain/MapDetailDTO.java
backend/src/main/resources/org/scoula/like/property/mapper/LikePropertyMapper.xml

맵에서 매물을 찜할 수 있는 REST API 기능을 추가하였습니다.

Feat : add to REST API about like property

---

backend/src/main/java/org/scoula/like/report/controller/LikeReportController.java
backend/src/main/resources/org/scoula/like/dictionary/mapper/LikeDictionaryMapper.xml
backend/src/main/resources/org/scoula/like/report/mapper/LikeReportMapper.xml

멤버별 부동산 레포트 REST API 부분에 버그가 있어서 수정했습니다.

Hotfix : fix member report REST API

---

backend/.idea/dataSources.xml
backend/src/main/java/org/scoula/map/domain/MapClusterVO.java
backend/src/main/java/org/scoula/map/domain/MapDetailDTO.java
backend/src/main/resources/org/scoula/map/mapper/MapMapper.xml
frontend/src/pages/map/LeftPanel.vue
frontend/src/pages/map/MainMap.vue
frontend/src/pages/map/MapAnalyzing.vue
frontend/src/pages/map/SearchBar.vue

1. map point will be moved by selecting liked property
2. map movement updated

Feat : Map function updated movement by liked property

---

backend/src/main/java/org/scoula/config/ServletConfig.java
backend/src/main/java/org/scoula/report/controller/ReportController.java

Feat : controller of report

---

backend/src/main/java/org/scoula/report/service/ReportServiceImpl.java
backend/src/main/java/org/scoula/safety_inspection/service/ExtractUnicodeService.java

Hotfix: Fix code duplication

---

frontend/src/components/Header.vue
frontend/src/pages/app/Main.vue

굵직한 기능들은 완료!
페이지 전체에서 큰 오류들 해결하겠습니다

Feat : main - piece (almost func....)

---

backend/.idea/dataSources.xml
backend/estate.sql
backend/src/main/java/org/scoula/report/controller/ReportController.java
backend/src/main/java/org/scoula/report/mapper/ReportMapper.java
backend/src/main/java/org/scoula/report/service/ReportService.java
backend/src/main/java/org/scoula/report/service/ReportServiceImpl.java
backend/src/main/resources/org/scoula/report/mapper/ReportMapper.xml
frontend/src/api/reportApi.js
frontend/src/components/DonutChart.vue
frontend/src/pages/app/Report.vue
frontend/src/pages/mypage/MyReport.vue
frontend/src/router/index.js

1. my report page feature created
2. my report page map updated

Feat : report page feature

---

backend/estate.sql
backend/src/main/resources/org/scoula/like/property/mapper/LikePropertyMapper.xml
frontend/src/api/like/likePropertyApi.js
frontend/src/pages/map/LeftPanel.vue

Feat : like property matched with member

---

backend/estate.sql
backend/src/main/java/org/scoula/like/report/service/LikeReportServiceImpl.java
backend/src/main/java/org/scoula/map/domain/MapDetailDTO.java
backend/src/main/resources/org/scoula/report/mapper/ReportMapper.xml
frontend/src/api/like/likeReportApi.js
frontend/src/components/DonutChart.vue
frontend/src/pages/mypage/MyReport.vue

1. report page router updated
2. Myreport page DB updated

Update : report page update with DB

---

frontend/src/components/DonutChart.vue
frontend/src/pages/app/Report.vue

1. font color updated based on the risk status

Update : report paged updated with font color

---

backend/.idea/dataSources.xml
backend/src/main/java/org/scoula/report/mapper/ReportMapper.java
backend/src/main/java/org/scoula/safety_inspection/controller/SafetyInspectionController.java
backend/src/main/java/org/scoula/safety_inspection/infra/bml/service/BuildingManagementLedgerGeneralService.java
backend/src/main/java/org/scoula/safety_inspection/infra/bml/service/BuildingManagementLedgerMultiService.java
backend/src/main/java/org/scoula/safety_inspection/infra/cors/service/CopyOfRegisterGeneralService.java
backend/src/main/java/org/scoula/safety_inspection/infra/cors/service/CopyOfRegisterMultiService.java
backend/src/main/java/org/scoula/safety_inspection/service/SafetyInspectionService.java
backend/src/main/resources/org/scoula/report/mapper/ReportMapper.xml
frontend/src/components/QuickChat.vue
frontend/src/pages/map/LeftPanel.vue
frontend/src/pages/map/MapAnalyzing.vue

BE test integration safety inspection

---

backend/estate.sql
backend/src/main/java/org/scoula/report/domain/ReportDTO.java
backend/src/main/java/org/scoula/report/domain/ReportVO.java
backend/src/main/java/org/scoula/report/service/ReportServiceImpl.java
backend/src/main/java/org/scoula/safety_inspection/infra/cors/dto/CopyOfRegisterDto.java
backend/src/main/java/org/scoula/safety_inspection/infra/cors/service/CopyOfRegisterGeneralService.java
backend/src/main/java/org/scoula/safety_inspection/infra/cors/service/CopyOfRegisterMultiService.java
backend/src/main/java/org/scoula/test/common/Payload.java
backend/src/main/java/org/scoula/test/controller/TestController.java
frontend/src/pages/Test.vue

report analysis 서비스를 테스트하는 코드를 추가하였습니다.

Be test report analysis

---

backend/src/main/java/org/scoula/chat/service/chatbot/ChatBotService.java
backend/src/main/java/org/scoula/chat/service/scenario/ScenarioService.java
frontend/src/components/QuickChat.vue
frontend/src/pages/scenario/ScenarioMain.vue

Fe test all

---

backend/estate.sql
backend/src/main/java/org/scoula/report/service/ReportServiceImpl.java
frontend/src/pages/Test.vue
frontend/src/pages/map/MapAnalyzing.vue

안전진단 중 계약자를 적지 않았을 때 불일치로 뜨는 버그를 수정하였습니다.

Fix : accord owner in report page

---

backend/.idea/dataSources.xml
backend/estate.sql
backend/src/main/java/org/scoula/oauth/jwt/filter/JwtAuthenticationFilter.java
backend/src/main/java/org/scoula/report/service/ReportServiceImpl.java
frontend/src/components/Header.vue
frontend/src/pages/Login.vue
frontend/src/pages/Test.vue
frontend/src/pages/map/MapAnalyzing.vue
frontend/src/pages/mypage/MyInfo.vue
frontend/src/pages/mypage/MyReport.vue
frontend/src/pages/mypage/Mypage.vue
frontend/src/pages/scenario/ScenarioMain.vue
frontend/src/pages/study/dictionary/DictionaryListPage.vue
frontend/src/router/index.js

- 3억 0만원 표시되는 문제
- myPage 컴포넌트화
- 컴포넌트 내 비로그인 유저 인증
- 시나리오 버튼 클릭 전체 색상으로 수정

Fe fix all UI

---

backend/estate.sql
backend/src/main/java/org/scoula/report/domain/ReportDTO.java
backend/src/main/java/org/scoula/report/domain/ReportVO.java
backend/src/main/java/org/scoula/report/service/ReportServiceImpl.java
backend/src/main/resources/org/scoula/report/mapper/ReportMapper.xml
frontend/src/pages/app/Report.vue
frontend/src/pages/map/MapAnalyzing.vue
frontend/src/pages/mypage/MyReport.vue

마이 레포트 페이지에 있는 날짜 및 점수 등급을 추가하였습니다.

Update : date and score level in my report page

---

frontend/src/pages/map/LeftPanel.vue

맵 페이지에서 상세보기 란에 즐겨찾기가 풀려있는 버그를 수정하였습니다.

fix : like property in leftPanel

---

frontend/src/pages/mypage/MyInfo.vue

마이페이지 정보 업데이트 버튼 오른쪽으로 정렬 및 버튼 형식으로 수정

fix : submit button aligning right in my page

---

frontend/src/pages/study/commonsense/SenseListPage.vue

Design : modal-card

---

backend/estate.sql

estate.sql에 레포트 샘플 넣는 방법을 추가하였습니다.

Feat : sample report for test

---

frontend/src/pages/map/MainMap.vue

Fix : map size

---

backend/src/main/java/org/scoula/safety_inspection/service/ExtractUnicodeService.java
frontend/src/pages/map/MapAnalyzing.vue

Feat : error code in report form

---

frontend/src/pages/map/MainMap.vue

맵의 매물을 클릭했을 때 생기는 버그를 수정하였습니다.

Fix : hover in map

---

frontend/src/components/DonutChart.vue
frontend/src/pages/app/Report.vue

[Design : report - toggle , Fix : report - algorithm , Design : DonutChart - score]

[Design : report - toggle , Fix : report - algorithm , Design : DonutChart - score]

---

backend/estate.sql
backend/src/main/java/org/scoula/safety_inspection/infra/cors/service/CopyOfRegisterMultiService.java
backend/src/main/java/org/scoula/safety_inspection/service/ExtractUnicodeService.java
backend/src/main/java/org/scoula/safety_inspection/service/SafetyInspectionService.java

Fix ExtractUnicodeService and SafetyInspectionService

---

backend/estate.sql
backend/src/main/java/org/scoula/report/service/ReportServiceImpl.java
backend/src/main/java/org/scoula/safety_inspection/service/SafetyInspectionService.java
backend/src/main/java/org/scoula/test/common/Payload.java
backend/src/main/java/org/scoula/test/controller/TestController.java
backend/src/main/resources/org/scoula/report/mapper/ReportMapper.xml
frontend/src/pages/Test.vue

마이 레포트 페이지에 날짜가 나오지 않는 버그를 수정하였습니다.

Fix : date in my report page

---

frontend/src/pages/mypage/MyReport.vue

Fix : delete delete button in my report page

---

frontend/src/pages/app/Introduce.vue
frontend/src/pages/app/Main.vue
frontend/src/pages/mypage/MyInfo.vue

Design : Final

---

frontend/src/api/mapApi.js
frontend/src/pages/map/LeftPanel.vue
frontend/src/pages/map/MainMap.vue
frontend/src/pages/map/SearchBar.vue

Design : searcg bar
